name: Docker CI & Sync

on:
  push:
    branches: ["main"]

jobs:
  build-and-sync:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Image
        run: |
          docker build -t rag-api:test -f Dockerfile.fastapi .

      - name: Build UI Image
        run: |
          docker build -t rag-ui:test -f Dockerfile.streamlit .

      - name: Push to Hugging Face
        env:
          HF_SYNC: ${{ secrets.HF_SYNC}}
        run: |
          git config --global user.email "azarudeen48@gmail.com"
          git config --global user.name "Azar-Mhmd"
          git remote rm hf || true
          git remote add hf https://Azar-Mhmd:$HF_SYNC@huggingface.co/spaces/Azar-Mhmd/ai-resume-intelligence
          git push --force hf main